#!/usr/bin sh

if [ "$#" -ne "1" ]; then
    echo "Usage: create-nginx NAME"
else
	sudo echo "server {
        	listen 80;
	    	listen [::]:80;

	        root /var/www/$1/dist;
        	index index.html index.htm index.nginx-debian.html;

	        server_name $1;

        	location / {
                	try_files "\$uri" "\$uri"/ =404;
	        }
	}" > /etc/nginx/sites-available/$1

	sudo ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled
fi
