#!/bin/bash 

if [ "$#" -ne "1" ]; then
    echo "Usage: create-site DOMAINNAME"
else
	siteFolder=$1

    echo "Creating site folder in /var/www..."'\n'
	sudo mkdir /var/www/$siteFolder

	echo "Creating nginx files..."'\n'
	~/dns-scripts/create-nginx $siteFolder

	echo "Creating Cloudflare CNAME DNS Record..."'\n'	
	~/dns-scripts/create-dns $siteFolder

	echo "Checking nginx syntax..."'\n'
	sudo nginx -t

    echo '\n'"Done."
	echo "Please sudo systemctl restart nginx to activate new site"
fi
